# Generated by Django 5.0.7 on 2024-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_desc', models.TextField()),
                ('food_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
